"""Report generator — PDF, HTML, CSV, JSON exports with CATSHY branding"""
import json
import csv
import io
from datetime import datetime
from typing import List, Dict, Optional
from jinja2 import Template

REPORT_HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} — {{ company_name }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', system-ui, sans-serif; background: #0d1117; color: #c9d1d9; line-height: 1.6; }
        .container { max-width: 900px; margin: 0 auto; padding: 40px 24px; }
        .header { border-bottom: 2px solid #00bcd4; padding-bottom: 24px; margin-bottom: 32px; }
        .header h1 { font-size: 28px; color: #e6edf3; margin-bottom: 8px; }
        .header .meta { color: #8b949e; font-size: 14px; }
        .brand { color: #00bcd4; font-weight: 700; letter-spacing: 2px; font-size: 12px; text-transform: uppercase; }
        .section { margin-bottom: 32px; }
        .section h2 { font-size: 20px; color: #e6edf3; border-left: 3px solid #00bcd4; padding-left: 12px; margin-bottom: 16px; }
        .section h3 { font-size: 16px; color: #c9d1d9; margin: 16px 0 8px; }
        .section p, .section li { color: #8b949e; font-size: 14px; margin-bottom: 8px; }
        .section ul { padding-left: 20px; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }
        .badge-critical { background: rgba(248,81,73,0.2); color: #f85149; border: 1px solid rgba(248,81,73,0.3); }
        .badge-high { background: rgba(210,153,34,0.2); color: #d29922; border: 1px solid rgba(210,153,34,0.3); }
        .badge-medium { background: rgba(56,139,253,0.2); color: #388bfd; border: 1px solid rgba(56,139,253,0.3); }
        .evidence { background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 16px; margin: 12px 0; font-family: monospace; font-size: 13px; white-space: pre-wrap; }
        .score-card { background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 16px; margin: 12px 0; }
        .score-card .score { font-size: 36px; font-weight: 700; color: #00bcd4; }
        .score-card .label { color: #8b949e; font-size: 12px; text-transform: uppercase; }
        .factor { display: flex; justify-content: space-between; padding: 4px 0; border-bottom: 1px solid #21262d; }
        table { width: 100%; border-collapse: collapse; margin: 12px 0; }
        th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #21262d; font-size: 14px; }
        th { color: #e6edf3; font-weight: 600; }
        .footer { margin-top: 48px; padding-top: 24px; border-top: 1px solid #30363d; color: #484f58; font-size: 12px; text-align: center; }
        .provenance { background: #0d1117; border-left: 3px solid #30363d; padding: 8px 12px; margin: 8px 0; font-size: 13px; color: #8b949e; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="brand">{{ company_name }} — Threat Intelligence Report</div>
            <h1>{{ title }}</h1>
            <div class="meta">
                Generated: {{ generated_at }} | Format: {{ format }} | Classification: {{ classification }}
            </div>
        </div>

        {% for section in sections %}
        <div class="section">
            <h2>{{ section.heading }}</h2>
            {% if section.type == 'narrative' %}
                <p>{{ section.content }}</p>
            {% elif section.type == 'evidence' %}
                <div class="evidence">{{ section.content }}</div>
            {% elif section.type == 'scoring' %}
                <div class="score-card">
                    {{ section.content }}
                </div>
            {% elif section.type == 'assets' %}
                <table>
                    <tr><th>Asset</th><th>Type</th><th>Criticality</th></tr>
                    {{ section.content }}
                </table>
            {% elif section.type == 'recommendations' %}
                <ul>{{ section.content }}</ul>
            {% else %}
                <p>{{ section.content }}</p>
            {% endif %}
        </div>
        {% endfor %}

        <div class="footer">
            <p>{{ company_name }} Threat Intelligence Platform — Confidential</p>
            <p>Report ID: {{ report_id }} | Generated by {{ generated_by }}</p>
        </div>
    </div>
</body>
</html>
"""

def generate_html_report(title: str, sections: list, metadata: dict) -> str:
    template = Template(REPORT_HTML_TEMPLATE)
    return template.render(
        title=title,
        sections=sections,
        company_name=metadata.get("company_name", "CATSHY"),
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        format=metadata.get("format", "HTML"),
        classification=metadata.get("classification", "TLP:AMBER"),
        report_id=metadata.get("report_id", "N/A"),
        generated_by=metadata.get("generated_by", "System"),
    )

def generate_pdf_report(title: str, sections: list, metadata: dict) -> bytes:
    """Generate PDF using WeasyPrint from HTML template."""
    html_content = generate_html_report(title, sections, metadata)
    try:
        from weasyprint import HTML
        return HTML(string=html_content).write_pdf()
    except ImportError:
        raise RuntimeError("WeasyPrint not installed. Install with: pip install weasyprint")

def generate_csv_report(items: list, fields: list) -> str:
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=fields, extrasaction="ignore")
    writer.writeheader()
    for item in items:
        writer.writerow(item)
    return output.getvalue()

def generate_json_report(title: str, sections: list, metadata: dict, items: list = None) -> str:
    report = {
        "title": title,
        "metadata": {**metadata, "generated_at": datetime.utcnow().isoformat()},
        "sections": sections,
    }
    if items:
        report["items"] = items
    return json.dumps(report, indent=2, default=str)
